<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SPARQLAS"
    nsURI="http://west.uni-koblenz.de/SPARQLAS" nsPrefix="SPARQLAS">
  <eClassifiers xsi:type="ecore:EClass" name="OntologyDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefixDefinition" ordered="false"
        upperBound="-1" eType="#//PrefixDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" ordered="false"
        lowerBound="1" eType="#//Query" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pref" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false"
        lowerBound="1" eType="#//FullIRI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryIRI" ordered="false"
        eType="#//IRI" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atoms" upperBound="-1"
        eType="#//Atom" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassVariable" eSuperTypes="#//Variable #//ClassExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyVariable" eSuperTypes="#//Variable #//ObjectPropertyExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyVariable" eSuperTypes="#//Variable #//DataPropertyExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualVariable" eSuperTypes="#//Variable #//Individual"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//ClassExpression #//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty" eSuperTypes="#//ObjectPropertyExpression #//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//DataPropertyExpression #//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedIndividual" eSuperTypes="#//Individual #//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousIndividual" eSuperTypes="#//Individual">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeID" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalForm" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" ordered="false"
        lowerBound="1" eType="#//Datatype" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAtom" abstract="true" eSuperTypes="#//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentClasses" eSuperTypes="#//ClassAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubClassOf" eSuperTypes="#//ClassAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subClassExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClassExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointClasses" eSuperTypes="#//ClassAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyAtom" abstract="true"
      eSuperTypes="#//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true" eSuperTypes="#//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetIndividual" ordered="false"
        lowerBound="1" eType="#//Individual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetValue" ordered="false"
        lowerBound="1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" ordered="false"
        lowerBound="1" eType="#//Individual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SameIndividual" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//Individual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifferentIndividuals" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//Individual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentObjectProperties" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//ObjectPropertyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubPropertyOf" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subObjectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superObjectPropertyExpression"
        lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="InverseObjectProperty" eSuperTypes="#//ObjectPropertyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" ordered="false"
        lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InverseObjectPropertyAtom" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression1"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression2"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalObjectProperty" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InverseFunctionalObjectProperty" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitiveObjectProperty" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymmetricObjectProperty" eSuperTypes="#//ObjectPropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectUnionOf" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectComplementOf" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectOneOf" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Individual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIntersectionOf" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAllValuesFrom" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSomeValuesFrom" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectHasValue" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" ordered="false"
        lowerBound="1" eType="#//Individual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMinCardinality" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMaxCardinality" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExactCardinality" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataHasValue" eSuperTypes="#//ClassExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" ordered="false"
        lowerBound="1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        lowerBound="1" eType="#//DataPropertyExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRI" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FullIRI" eSuperTypes="#//IRI"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbbreviatedIRI" eSuperTypes="#//IRI"/>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true" eSuperTypes="#//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyVariable"
        lowerBound="1" eType="#//ObjectPropertyVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypePropertyDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatypePropertyVariable"
        lowerBound="1" eType="#//DataPropertyVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualVariable" lowerBound="1"
        eType="#//IndividualVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classVariable" lowerBound="1"
        eType="#//ClassVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantIRI" lowerBound="1"
        eType="#//IRI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true"/>
</ecore:EPackage>
