<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="owl"
    nsURI="http:///owl.ecore" nsPrefix="owl2">
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true" eSuperTypes="#//Axiom"/>
  <eClassifiers xsi:type="ecore:EClass" name="Axiom" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axiomAnnotations" ordered="false"
        upperBound="-1" eType="#//Annotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationProperty" ordered="false"
        lowerBound="1" eType="#//AnnotationProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationProperty" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityURI" lowerBound="1"
        eType="#//URI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Constant #//DObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" ordered="false"
        lowerBound="1" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//DataRange #//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataTypeMaps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataRange" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arity" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyAxiom" abstract="true" eSuperTypes="#//Axiom"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyAxiom" abstract="true"
      eSuperTypes="#//Axiom"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAxiom" abstract="true" eSuperTypes="#//Axiom"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFunctional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInverseFunctional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIrreflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSymmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAsysmmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsymmetricObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty" eSuperTypes="#//Entity #//ObjectPropertyExpression #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InverseObjectProperty" eSuperTypes="#//ObjectPropertyExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" ordered="false"
        lowerBound="1" eType="#//ObjectProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Entity #//ClassExpression #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIntersectionOf" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectOneOf" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" abstract="true" eSuperTypes="#//Constant #//IObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedIndividual" eSuperTypes="#//Entity #//Individual #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSomeValuesFrom" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAllValuesFrom" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExistsSelf" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectHasValue" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMinCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMaxCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSomeValuesFrom" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        lowerBound="1" eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpressions"
        lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//Entity #//DataPropertyExpression #//ParameterableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataOneOf" eSuperTypes="#//DataRange #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeRestriction" eSuperTypes="#//DataRange #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" ordered="false"
        lowerBound="1" eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictions" ordered="false"
        upperBound="-1" eType="#//FacetConstantPair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetConstantPair">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="self.facet = 'length' &#xD;&#xA;or self.facet = 'minLength' &#xD;&#xA;or self.facet = 'maxLength' &#xD;&#xA;or self.facet = 'pattern' &#xD;&#xA;or self.facet = 'minInclusive' &#xD;&#xA;or self.facet = 'minExclusive' &#xD;&#xA;or self.facet = 'maxInclusive'&#xD;&#xA;or self.facet = 'maxExclusive'&#xD;&#xA;or self.facet = 'totalDigits' &#xD;&#xA;or self.facet = 'fractionDigits'&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false"
        lowerBound="1" eType="#//Literal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="facet" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAllValuesFrom" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        lowerBound="1" eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpressions"
        lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataHasValue" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false"
        lowerBound="1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMinCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMaxCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataExactCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeDataPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetValue" ordered="false"
        lowerBound="1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyDomain" eSuperTypes="#//DataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyRange" eSuperTypes="#//DataPropertyAxiom">
    <eOperations name="Thedatarangemustbeofarityone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{self.range.arity = 1}"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" ordered="false"
        lowerBound="1" eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifferentIndividuals" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="differentIndividuals" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//NamedIndividual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointClasses" eSuperTypes="#//ClassAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointClassExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointDataProperties" eSuperTypes="#//DataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointObjectProperties" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisjointUnion" eSuperTypes="#//ClassAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unionClass" ordered="false"
        lowerBound="1" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjointClassExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentClasses" eSuperTypes="#//ClassAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalentClassExpressions"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentDataProperties" eSuperTypes="#//DataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalentObjectProperties" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpressions"
        ordered="false" lowerBound="2" upperBound="-1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalDataProperty" eSuperTypes="#//DataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InverseFunctionalObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeObjectPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyDomain" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymmetricObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReflexiveObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubDataPropertyOf" eSuperTypes="#//DataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superDataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subDataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SameIndividual" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sameIndividuals" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//NamedIndividual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubObjectPropertyOf" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superObjectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subObjectPropertyExpressions"
        lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectComplementOf" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ontology">
    <eOperations name="versionURIrequiresontologyURItobespecified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.versionURI != 0 implies self.ontologyURI != 0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontologyAnnotations" ordered="false"
        upperBound="-1" eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axioms" ordered="false"
        upperBound="-1" eType="#//Axiom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedOntologies" ordered="false"
        upperBound="-1" eType="#//Ontology"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" ordered="false"
        upperBound="-1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ontologyURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectPropertyRange" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpression"
        ordered="false" lowerBound="1" eType="#//DataPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetValue" lowerBound="1"
        eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceIndividual" ordered="false"
        lowerBound="1" eType="#//Individual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual" ordered="false"
        lowerBound="1" eType="#//NamedIndividual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IrreflexiveObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExactCardinality" eSuperTypes="#//ClassExpression #//Expression">
    <eOperations name="Thecardinalitymustbenonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.cardinality>=0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataComplementOf" eSuperTypes="#//DataRange #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRange" ordered="false"
        lowerBound="1" eType="#//DataRange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubClassOf" eSuperTypes="#//ClassAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subClassExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClassExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubObjectProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransitiveObjectProperty" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpression"
        ordered="false" lowerBound="1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityAnnotation" eSuperTypes="#//Axiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" ordered="false"
        lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityAnnotations" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Annotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FullURI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iri" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbbreviatedURI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectUnionOf" eSuperTypes="#//ClassExpression #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpressions" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//ClassExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InverseObjectProperties" eSuperTypes="#//ObjectPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObjectPropertyExpression1"
        ordered="false" eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObjectPropertyExpression2"
        ordered="false" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationByConstant" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationValue" ordered="false"
        lowerBound="1" eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationByEntity" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationValue" ordered="false"
        lowerBound="1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationByAnonymousIndividual" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotationValue" ordered="false"
        lowerBound="1" eType="#//AnonymousIndividual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousIndividual" eSuperTypes="#//Individual">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeID" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" eSuperTypes="#//Axiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFunctional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInverseFunctional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIrreflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSymmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAsysmmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAndDataPropertyAxiom" abstract="true"
      eSuperTypes="#//Axiom"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyFor" eSuperTypes="#//ObjectAndDataPropertyAxiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classExpression" ordered="false"
        lowerBound="1" eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPropertyExpressions"
        ordered="false" upperBound="-1" eType="#//DataPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyExpressions"
        ordered="false" upperBound="-1" eType="#//ObjectPropertyExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousIndividualAnnotation" eSuperTypes="#//Axiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousIndividual" ordered="false"
        lowerBound="1" eType="#//AnonymousIndividual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousIndiviudalAnnotations"
        ordered="false" lowerBound="1" upperBound="-1" eType="#//Annotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OntologyDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontology" lowerBound="1"
        eType="#//Ontology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrefixDefinition" lowerBound="1"
        upperBound="-1" eType="#//PrefixDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrefixDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//FullURI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameteredElement"
        eType="#//ParameterableElement" containment="true" eOpposite="#//ParameterableElement/owningTemplateParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//TemplateSignature" eOpposite="#//TemplateSignature/ownedParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameteredElement" lowerBound="1"
        eType="#//ParameterableElement" eOpposite="#//ParameterableElement/templateParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningTemplateParameter"
        eType="#//TemplateParameter" eOpposite="#//TemplateParameter/ownedParameteredElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateParameter" eType="#//TemplateParameter"
        eOpposite="#//TemplateParameter/parameteredElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateSignature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        upperBound="-1" eType="#//TemplateParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" upperBound="-1"
        eType="#//TemplateParameter" containment="true" eOpposite="#//TemplateParameter/signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
        eType="#//TemplateableElement" eOpposite="#//TemplateableElement/ownedTemplateSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTemplateSignature"
        eType="#//TemplateSignature" containment="true" eOpposite="#//TemplateSignature/template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" upperBound="-1"
        eType="#//TemplateBinding" containment="true" eOpposite="#//TemplateBinding/boundElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//TemplateableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" ordered="false"
        upperBound="-1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axioms" ordered="false"
        upperBound="-1" eType="#//Axiom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PackageUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierTemplateParameter" eSuperTypes="#//TemplateParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateParameterSubstitution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actual" lowerBound="1"
        eType="#//ParameterableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formal" lowerBound="1"
        eType="#//TemplateParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" lowerBound="1"
        eType="#//TemplateBinding" eOpposite="#//TemplateBinding/parameterSubstitution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterSubstitution"
        upperBound="-1" eType="#//TemplateParameterSubstitution" containment="true"
        eOpposite="#//TemplateParameterSubstitution/templateBinding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundElement" lowerBound="1"
        eType="#//TemplateableElement" eOpposite="#//TemplateableElement/templateBinding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//TemplateSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypeMaps">
    <eLiterals name="integer" literal="xsd:integer"/>
    <eLiterals name="string" literal="xsd:string"/>
    <eLiterals name="boolean" literal="xsd:boolean"/>
    <eLiterals name="byte" literal="xsd:byte"/>
    <eLiterals name="decimal" literal="xsd:decimal"/>
    <eLiterals name="float" literal="xsd:float"/>
    <eLiterals name="double" literal="xsd:double"/>
    <eLiterals name="data" literal="xsd:data"/>
    <eLiterals name="duration" literal="xsd:duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//Axiom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAntecedent" lowerBound="1"
        eType="#//Antecedent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasConsequent" lowerBound="1"
        eType="#//Consequent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swrlVariables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Antecedent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsAtoms" upperBound="-1"
        eType="#//Atom" containment="true" eOpposite="#//Atom/isInAntecedent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consequent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsAtoms" upperBound="-1"
        eType="#//Atom" containment="true" eOpposite="#//Atom/isInConsequent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInConsequent" eType="#//Consequent"
        eOpposite="#//Consequent/containsAtoms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInAntecedent" eType="#//Antecedent"
        eOpposite="#//Antecedent/containsAtoms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataRangeAtom" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPredicateSymbol" lowerBound="1"
        eType="#//DataRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTerm" lowerBound="1"
        eType="#//DObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAtom" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPredicateSymbol" lowerBound="1"
        eType="#//ClassExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTerm" lowerBound="1"
        eType="#//IObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAtom" abstract="true" eSuperTypes="#//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualPropetyAtom" eSuperTypes="#//PropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPredicateSymbol" lowerBound="1"
        eType="#//ObjectPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomTarget" lowerBound="1"
        eType="#//ClassAtom" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomSource" lowerBound="1"
        eType="#//ClassAtom" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatavaluedPropertyAtom" eSuperTypes="#//PropertyAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPredicateSymbol" lowerBound="1"
        eType="#//DataPropertyExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomTarget" lowerBound="1"
        eType="#//DataRangeAtom" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomSource" lowerBound="1"
        eType="#//DataRangeAtom" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataVariable" eSuperTypes="#//Variable #//DObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualVariable" eSuperTypes="#//Variable #//IObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInAtom" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasPredicateSymbol" lowerBound="1"
        eType="#//BuiltInID" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTerms" upperBound="-1"
        eType="#//DObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInID">
    <eLiterals name="EQUAL" literal="swrlb:equal"/>
    <eLiterals name="NOT_EQUAL" literal="swrlb:notEqual"/>
  </eClassifiers>
</ecore:EPackage>
