/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package west.twouse.language.yuml.resource.yuml.grammar;

public class YumlGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public static class Rule extends west.twouse.language.yuml.resource.yuml.grammar.YumlSyntaxElement {
		
		private final org.eclipse.emf.ecore.EClass metaclass;
		
		public Rule(org.eclipse.emf.ecore.EClass metaclass, west.twouse.language.yuml.resource.yuml.grammar.YumlChoice choice, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality cardinality) {
			super(cardinality, new west.twouse.language.yuml.resource.yuml.grammar.YumlSyntaxElement[] {choice});
			this.metaclass = metaclass;
		}
		
		public org.eclipse.emf.ecore.EClass getMetaclass() {
			return metaclass;
		}
		
		public west.twouse.language.yuml.resource.yuml.grammar.YumlChoice getDefinition() {
			return (west.twouse.language.yuml.resource.yuml.grammar.YumlChoice) getChildren()[0];
		}
	}
	
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_0_0_0_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getModel().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.MODEL__ELEMENTS), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_0_0_0_0_0_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(",", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlLineBreak YUML_0_0_0_0_0_0_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlLineBreak(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_0_0_0_0_0_0_1_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getModel().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.MODEL__ELEMENTS), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_0_0_0_0_0_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0_0_0_0_1_0_0_0, YUML_0_0_0_0_0_0_1_0_0_1, YUML_0_0_0_0_0_0_1_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_0_0_0_0_0_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0_0_0_0_1_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_0_0_0_0_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_0_0_0_0_0_0_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.STAR);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_0_0_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0_0_0_0_0, YUML_0_0_0_0_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_0_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_0_0_0_0_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_0_0_0);
	public final static Rule YUML_0 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getModel(), YUML_0_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("[", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("<<", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_1_0_0_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__STEREOTYPE), "ALPHANUM", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_1_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(">>", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_1_0_0_0, YUML_1_0_0_1_0_0_1, YUML_1_0_0_1_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_1_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_1_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__NAME), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_3_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("|", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_1_0_0_3_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__ATTRIBUTES), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_3_0_0_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(";", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_1_0_0_3_0_0_2_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__ATTRIBUTES), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_3_0_0_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_3_0_0_2_0_0_0, YUML_1_0_0_3_0_0_2_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_3_0_0_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_3_0_0_2_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_3_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_3_0_0_2_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.STAR);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_3_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_3_0_0_0, YUML_1_0_0_3_0_0_1, YUML_1_0_0_3_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_3_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_3_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_3_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_4_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("|", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_1_0_0_4_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__METHODS), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_4_0_0_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(";", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_1_0_0_4_0_0_2_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__METHODS), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_4_0_0_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_4_0_0_2_0_0_0, YUML_1_0_0_4_0_0_2_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_4_0_0_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_4_0_0_2_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_4_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_4_0_0_2_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.STAR);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_4_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_4_0_0_0, YUML_1_0_0_4_0_0_1, YUML_1_0_0_4_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_4_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_4_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_4 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_4_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_5_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("{bg:", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_1_0_0_5_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CLASS__COLOR), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_5_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("}", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0_5_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_5_0_0_0, YUML_1_0_0_5_0_0_1, YUML_1_0_0_5_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0_0_5_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_5_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_1_0_0_5 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_1_0_0_5_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_1_0_0_6 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("]", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0_0, YUML_1_0_0_1, YUML_1_0_0_2, YUML_1_0_0_3, YUML_1_0_0_4, YUML_1_0_0_5, YUML_1_0_0_6);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_1_0_0);
	public final static Rule YUML_1 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getClass_(), YUML_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__SOURCE), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlBooleanTerminal YUML_2_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlBooleanTerminal(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__NAVIGABLE_SOURCE), "<", "", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_2_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__SOURCE_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_2_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__SOURCE_CARDINALITY), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_2_0_0_4 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("-", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_2_0_0_5 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__TARGET_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_2_0_0_6 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__TARGET_CARDINALITY), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlBooleanTerminal YUML_2_0_0_7 = new west.twouse.language.yuml.resource.yuml.grammar.YumlBooleanTerminal(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__NAVIGABLE_TARGET), ">", "", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_2_0_0_8 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ASSOCIATION__TARGET), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_2_0_0_0, YUML_2_0_0_1, YUML_2_0_0_2, YUML_2_0_0_3, YUML_2_0_0_4, YUML_2_0_0_5, YUML_2_0_0_6, YUML_2_0_0_7, YUML_2_0_0_8);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_2_0_0);
	public final static Rule YUML_2 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAssociation(), YUML_2_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_0_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__SOURCE), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_3_0_0_0_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("^", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_0_0_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__TARGET), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_0_0_0_0_0, YUML_3_0_0_0_0_0_1, YUML_3_0_0_0_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_3_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_0_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_3_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_3_0_0_0_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_1_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__SOURCE), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_3_0_1_0_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("-", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_3_0_1_0_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__TARGET_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_3_0_1_0_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("^", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_1_0_0_0_4 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__TARGET), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_1_0_0_0_0, YUML_3_0_1_0_0_0_1, YUML_3_0_1_0_0_0_2, YUML_3_0_1_0_0_0_3, YUML_3_0_1_0_0_0_4);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_3_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_1_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_3_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_3_0_1_0_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_1_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_2_0_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__TARGET), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_3_0_2_0_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("^", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_3_0_2_0_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__TARGET_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_3_0_2_0_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("-", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_3_0_2_0_0_0_4 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.INHERITANCE__SOURCE), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_2_0_0_0_0, YUML_3_0_2_0_0_0_1, YUML_3_0_2_0_0_0_2, YUML_3_0_2_0_0_0_3, YUML_3_0_2_0_0_0_4);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_3_0_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_2_0_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_3_0_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_3_0_2_0_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_3_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_2_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_3_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_3_0_0, YUML_3_0_1, YUML_3_0_2);
	public final static Rule YUML_3 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getInheritance(), YUML_3_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_4_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getCardinality().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CARDINALITY__LOWER_BOUND), "CARDINALITY", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_4_0_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("..", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_4_0_0_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getCardinality().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.CARDINALITY__UPPER_BOUND), "CARDINALITY", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_4_0_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_4_0_0_1_0_0_0, YUML_4_0_0_1_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_4_0_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_4_0_0_1_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_4_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_4_0_0_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_4_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_4_0_0_0, YUML_4_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_4_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_4_0_0);
	public final static Rule YUML_4 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getCardinality(), YUML_4_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_5_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAttribute().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ATTRIBUTE__VISIBILITY), "VISIBILITY", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_5_0_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("<<", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_5_0_0_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAttribute().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ATTRIBUTE__STEREOTYPE), "ALPHANUM", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_5_0_0_1_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(">>", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_5_0_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0_1_0_0_0, YUML_5_0_0_1_0_0_1, YUML_5_0_0_1_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_5_0_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0_1_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_5_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_5_0_0_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_5_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAttribute().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ATTRIBUTE__NAME), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_5_0_0_3_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(" : ", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_5_0_0_3_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAttribute().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.ATTRIBUTE__TYPE), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_5_0_0_3_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0_3_0_0_0, YUML_5_0_0_3_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_5_0_0_3_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0_3_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_5_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_5_0_0_3_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_5_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0_0, YUML_5_0_0_1, YUML_5_0_0_2, YUML_5_0_0_3);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_5_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_5_0_0);
	public final static Rule YUML_5 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getAttribute(), YUML_5_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_6_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getMethod().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.METHOD__NAME), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_6_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("(", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_6_0_0_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getMethod().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.METHOD__ARGUMENTS), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_6_0_0_2_0_0_1_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(",", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_6_0_0_2_0_0_1_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getMethod().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.METHOD__ARGUMENTS), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_6_0_0_2_0_0_1_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0_2_0_0_1_0_0_0, YUML_6_0_0_2_0_0_1_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_6_0_0_2_0_0_1_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0_2_0_0_1_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_6_0_0_2_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_6_0_0_2_0_0_1_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.STAR);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_6_0_0_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0_2_0_0_0, YUML_6_0_0_2_0_0_1);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_6_0_0_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0_2_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_6_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_6_0_0_2_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_6_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword(")", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_6_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0_0, YUML_6_0_0_1, YUML_6_0_0_2, YUML_6_0_0_3);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_6_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_6_0_0);
	public final static Rule YUML_6 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getMethod(), YUML_6_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_7_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("[note: ", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_7_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getNote().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.NOTE__TEXT), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_7_0_0_2_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("{bg:", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_7_0_0_2_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getNote().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.NOTE__COLOR), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_7_0_0_2_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("}", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_7_0_0_2_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_7_0_0_2_0_0_0, YUML_7_0_0_2_0_0_1, YUML_7_0_0_2_0_0_2);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_7_0_0_2_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_7_0_0_2_0_0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlCompound YUML_7_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlCompound(YUML_7_0_0_2_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_7_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("]", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_7_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_7_0_0_0, YUML_7_0_0_1, YUML_7_0_0_2, YUML_7_0_0_3);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_7_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_7_0_0);
	public final static Rule YUML_7 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getNote(), YUML_7_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_8_0_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getEquivalence().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.EQUIVALENCE__SOURCE), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_8_0_0_1 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("^", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_8_0_0_2 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getEquivalence().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.EQUIVALENCE__SOURCE_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_8_0_0_3 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("-", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder YUML_8_0_0_4 = new west.twouse.language.yuml.resource.yuml.grammar.YumlPlaceholder(west.twouse.language.yuml.YumlPackage.eINSTANCE.getEquivalence().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.EQUIVALENCE__TARGET_LABEL), "TEXT", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.QUESTIONMARK, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword YUML_8_0_0_5 = new west.twouse.language.yuml.resource.yuml.grammar.YumlKeyword("^", west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlContainment YUML_8_0_0_6 = new west.twouse.language.yuml.resource.yuml.grammar.YumlContainment(west.twouse.language.yuml.YumlPackage.eINSTANCE.getEquivalence().getEStructuralFeature(west.twouse.language.yuml.YumlPackage.EQUIVALENCE__TARGET), west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, 0);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlSequence YUML_8_0_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlSequence(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_8_0_0_0, YUML_8_0_0_1, YUML_8_0_0_2, YUML_8_0_0_3, YUML_8_0_0_4, YUML_8_0_0_5, YUML_8_0_0_6);
	public final static west.twouse.language.yuml.resource.yuml.grammar.YumlChoice YUML_8_0 = new west.twouse.language.yuml.resource.yuml.grammar.YumlChoice(west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE, YUML_8_0_0);
	public final static Rule YUML_8 = new Rule(west.twouse.language.yuml.YumlPackage.eINSTANCE.getEquivalence(), YUML_8_0, west.twouse.language.yuml.resource.yuml.grammar.YumlCardinality.ONE);
}
